export const GEN_1_POKEMON_MAP = {
    0x01: 'Rhydon',
    0x02: 'Kangaskhan',
    0x03: 'Nidoran♂',
    0x04: 'Clefairy',
    0x05: 'Spearow',
    0x06: 'Voltorb',
    0x07: 'Nidoking',
    0x08: 'Slowbro',
    0x09: 'Ivysaur',
    0x0a: 'Exeggutor',
    0x0b: 'Lickitung',
    0x0c: 'Exeggcute',
    0x0d: 'Grimer',
    0x0e: 'Gengar',
    0x0f: 'Nidoran♀',
    0x10: 'Nidoqueen',
    0x11: 'Cubone',
    0x12: 'Rhyhorn',
    0x13: 'Lapras',
    0x14: 'Arcanine',
    0x15: 'Mew',
    0x16: 'Gyarados',
    0x17: 'Shellder',
    0x18: 'Tentacool',
    0x19: 'Gastly',
    0x1a: 'Scyther',
    0x1b: 'Staryu',
    0x1c: 'Blastoise',
    0x1d: 'Pinsir',
    0x1e: 'Tangela',
    0x1f: 'MissingNo.(Scizor)',
    0x20: 'MissingNo.(Shuckle)',
    0x21: 'Growlithe',
    0x22: 'Onix',
    0x23: 'Fearow',
    0x24: 'Pidgey',
    0x25: 'Slowpoke',
    0x26: 'Kadabra',
    0x27: 'Graveler',
    0x28: 'Chansey',
    0x29: 'Machoke',
    0x2a: 'Mr.Mime',
    0x2b: 'Hitmonlee',
    0x2c: 'Hitmonchan',
    0x2d: 'Arbok',
    0x2e: 'Parasect',
    0x2f: 'Psyduck',
    0x30: 'Drowzee',
    0x31: 'Golem',
    0x32: 'MissingNo.(Heracross)',
    0x33: 'Magmar',
    0x34: 'MissingNo.(Ho-Oh)',
    0x35: 'Electabuzz',
    0x36: 'Magneton',
    0x37: 'Koffing',
    0x38: 'MissingNo.(Sneasel)',
    0x39: 'Mankey',
    0x3a: 'Seel',
    0x3b: 'Diglett',
    0x3c: 'Tauros',
    0x3d: 'MissingNo.(Teddiursa)',
    0x3e: 'MissingNo.(Ursaring)',
    0x3f: 'MissingNo.(Slugma)',
    0x40: "Farfetch'd",
    0x41: 'Venonat',
    0x42: 'Dragonite',
    0x43: 'MissingNo.(Magcargo)',
    0x44: 'MissingNo.(Swinub)',
    0x45: 'MissingNo.(Piloswine)',
    0x46: 'Doduo',
    0x47: 'Poliwag',
    0x48: 'Jynx',
    0x49: 'Moltres',
    0x4a: 'Articuno',
    0x4b: 'Zapdos',
    0x4c: 'Ditto',
    0x4d: 'Meowth',
    0x4e: 'Krabby',
    0x4f: 'MissingNo.(Corsola)',
    0x50: 'MissingNo.(Remoraid)',
    0x51: 'MissingNo.(Octillery)',
    0x52: 'Vulpix',
    0x53: 'Ninetales',
    0x54: 'Pikachu',
    0x55: 'Raichu',
    0x56: 'MissingNo.(Delibird)',
    0x57: 'MissingNo.(Mantine)',
    0x58: 'Dratini',
    0x59: 'Dragonair',
    0x5a: 'Kabuto',
    0x5b: 'Kabutops',
    0x5c: 'Horsea',
    0x5d: 'Seadra',
    0x5e: 'MissingNo.(Skarmory)',
    0x5f: 'MissingNo.(Houndour)',
    0x60: 'Sandshrew',
    0x61: 'Sandslash',
    0x62: 'Omanyte',
    0x63: 'Omastar',
    0x64: 'Jigglypuff',
    0x65: 'Wigglytuff',
    0x66: 'Eevee',
    0x67: 'Flareon',
    0x68: 'Jolteon',
    0x69: 'Vaporeon',
    0x6a: 'Machop',
    0x6b: 'Zubat',
    0x6c: 'Ekans',
    0x6d: 'Paras',
    0x6e: 'Poliwhirl',
    0x6f: 'Poliwrath',
    0x70: 'Weedle',
    0x71: 'Kakuna',
    0x72: 'Beedrill',
    0x73: 'MissingNo.(Houndoom)',
    0x74: 'Dodrio',
    0x75: 'Primeape',
    0x76: 'Dugtrio',
    0x77: 'Venomoth',
    0x78: 'Dewgong',
    0x79: 'MissingNo.(Kingdra)',
    0x7a: 'MissingNo.(Phanpy)',
    0x7b: 'Caterpie',
    0x7c: 'Metapod',
    0x7d: 'Butterfree',
    0x7e: 'Machamp',
    0x7f: 'MissingNo.(Donphan)',
    0x80: 'Golduck',
    0x81: 'Hypno',
    0x82: 'Golbat',
    0x83: 'Mewtwo',
    0x84: 'Snorlax',
    0x85: 'Magikarp',
    0x86: 'MissingNo.(Porygon2)',
    0x87: 'MissingNo.(Stantler)',
    0x88: 'Muk',
    0x89: 'MissingNo.(Smeargle)',
    0x8a: 'Kingler',
    0x8b: 'Cloyster',
    0x8c: 'MissingNo.(Tyrogue)',
    0x8d: 'Electrode',
    0x8e: 'Clefable',
    0x8f: 'Weezing',
    0x90: 'Persian',
    0x91: 'Marowak',
    0x92: 'MissingNo.(Hitmontop)',
    0x93: 'Haunter',
    0x94: 'Abra',
    0x95: 'Alakazam',
    0x96: 'Pidgeotto',
    0x97: 'Pidgeot',
    0x98: 'Starmie',
    0x99: 'Bulbasaur',
    0x9a: 'Venusaur',
    0x9b: 'Tentacruel',
    0x9c: 'MissingNo.(Smoochum)',
    0x9d: 'Goldeen',
    0x9e: 'Seaking',
    0x9f: 'MissingNo.(Elekid)',
    0xa0: 'MissingNo.(Magby)',
    0xa1: 'MissingNo.(Miltank)',
    0xa2: 'MissingNo.(Blissey)',
    0xa3: 'Ponyta',
    0xa4: 'Rapidash',
    0xa5: 'Rattata',
    0xa6: 'Raticate',
    0xa7: 'Nidorino',
    0xa8: 'Nidorina',
    0xa9: 'Geodude',
    0xaa: 'Porygon',
    0xab: 'Aerodactyl',
    0xac: 'MissingNo.(Raikou)',
    0xad: 'Magnemite',
    0xae: 'MissingNo.(Entei)',
    0xaf: 'MissingNo.(Suicune)',
    0xb0: 'Charmander',
    0xb1: 'Squirtle',
    0xb2: 'Charmeleon',
    0xb3: 'Wartortle',
    0xb4: 'Charizard',
    0xb5: 'MissingNo.(Larvitar)',
    0xb6: 'MissingNo.KabutopsFossil(Pupitar)',
    0xb7: 'MissingNo.AerodactylFossil(Tyranitar)',
    0xb8: 'MissingNo.Ghost(Lugia)',
    0xb9: 'Oddish',
    0xba: 'Gloom',
    0xbb: 'Vileplume',
    0xbc: 'Bellsprout',
    0xbd: 'Weepinbell',
    0xbe: 'Victreebel',
};

export const GEN_1_CHARACTER_MAP = {
    0x80: 'A',
    0x81: 'B',
    0x82: 'C',
    0x83: 'D',
    0x84: 'E',
    0x85: 'F',
    0x86: 'G',
    0x87: 'H',
    0x88: 'I',
    0x89: 'J',
    0x8a: 'K',
    0x8b: 'L',
    0x8c: 'M',
    0x8d: 'N',
    0x8e: 'O',
    0x8f: 'P',
    0x90: 'Q',
    0x91: 'R',
    0x92: 'S',
    0x93: 'T',
    0x94: 'U',
    0x95: 'V',
    0x96: 'W',
    0x97: 'X',
    0x98: 'Y',
    0x99: 'Z',
    0x9a: '(',
    0x9b: ')',
    0x9c: ':',
    0x9d: ';',
    0x9e: '[',
    0x9f: ']',
    0xa0: 'a',
    0xa1: 'b',
    0xa2: 'c',
    0xa3: 'd',
    0xa4: 'e',
    0xa5: 'f',
    0xa6: 'g',
    0xa7: 'h',
    0xa8: 'i',
    0xa9: 'j',
    0xaa: 'k',
    0xab: 'l',
    0xac: 'm',
    0xad: 'n',
    0xae: 'o',
    0xaf: 'p',
    0xb0: 'q',
    0xb1: 'r',
    0xb2: 's',
    0xb3: 't',
    0xb4: 'u',
    0xb5: 'v',
    0xb6: 'w',
    0xb7: 'x',
    0xb8: 'y',
    0xb9: 'z',
    0xba: 'é',
    0xbb: "'d",
    0xbc: "'l",
    0xbd: "'s",
    0xbe: "'t",
    0xbf: "'v",
    0xef: '♂',
    0xe0: "'",
    0xe4: '-',
    0xe7: '?',
    0xe8: '!',
    0xe9: '.',
    0xf2: '.',
    0xf3: '/',
    0xf4: ',',
    0xf5: '♀',
    0xf6: '0',
    0xf7: '1',
    0xf8: '2',
    0xf9: '3',
    0xfa: '4',
    0xfb: '5',
    0xfc: '6',
    0xfd: '7',
    0xfe: '8',
    0xff: '9',
};

export const MOVES_ARRAY = [
    // Array is 1-indexed
    '',
    'Pound',
    'Karate Chop',
    'Double Slap',
    'Comet Punch',
    'Mega Punch',
    'Pay Day',
    'Fire Punch',
    'Ice Punch',
    'Thunder Punch',
    'Scratch',
    'Vice Grip',
    'Guillotine',
    'Razor Wind',
    'Swords Dance',
    'Cut',
    'Gust',
    'Wing Attack',
    'Whirlwind',
    'Fly',
    'Bind',
    'Slam',
    'Vine Whip',
    'Stomp',
    'Double Kick',
    'Mega Kick',
    'Jump Kick',
    'Rolling Kick',
    'Sand Attack',
    'Headbutt',
    'Horn Attack',
    'Fury Attack',
    'Horn Drill',
    'Tackle',
    'Body Slam',
    'Wrap',
    'Take Down',
    'Thrash',
    'Double-Edge',
    'Tail Whip',
    'Poison Sting',
    'Twineedle',
    'Pin Missile',
    'Leer',
    'Bite',
    'Growl',
    'Roar',
    'Sing',
    'Supersonic',
    'Sonic Boom',
    'Disable',
    'Acid',
    'Ember',
    'Flamethrower',
    'Mist',
    'Water Gun',
    'Hydro Pump',
    'Surf',
    'Ice Beam',
    'Blizzard',
    'Psybeam',
    'Bubble Beam',
    'Aurora Beam',
    'Hyper Beam',
    'Peck',
    'Drill Peck',
    'Submission',
    'Low Kick',
    'Counter',
    'Seismic Toss',
    'Strength',
    'Absorb',
    'Mega Drain',
    'Leech Seed',
    'Growth',
    'Razor Leaf',
    'Solar Beam',
    'Poison Powder',
    'Stun Spore',
    'Sleep Powder',
    'Petal Dance',
    'String Shot',
    'Dragon Rage',
    'Fire Spin',
    'Thunder Shock',
    'Thunderbolt',
    'Thunder Wave',
    'Thunder',
    'Rock Throw',
    'Earthquake',
    'Fissure',
    'Dig',
    'Toxic',
    'Confusion',
    'Psychic',
    'Hypnosis',
    'Meditate',
    'Agility',
    'Quick Attack',
    'Rage',
    'Teleport',
    'Night Shade',
    'Mimic',
    'Screech',
    'Double Team',
    'Recover',
    'Harden',
    'Minimize',
    'Smokescreen',
    'Confuse Ray',
    'Withdraw',
    'Defense Curl',
    'Barrier',
    'Light Screen',
    'Haze',
    'Reflect',
    'Focus Energy',
    'Bide',
    'Metronome',
    'Mirror Move',
    'Self-Destruct',
    'Egg Bomb',
    'Lick',
    'Smog',
    'Sludge',
    'Bone Club',
    'Fire Blast',
    'Waterfall',
    'Clamp',
    'Swift',
    'Skull Bash',
    'Spike Cannon',
    'Constrict',
    'Amnesia',
    'Kinesis',
    'Soft-Boiled',
    'High Jump Kick',
    'Glare',
    'Dream Eater',
    'Poison Gas',
    'Barrage',
    'Leech Life',
    'Lovely Kiss',
    'Sky Attack',
    'Transform',
    'Bubble',
    'Dizzy Punch',
    'Spore',
    'Flash',
    'Psywave',
    'Splash',
    'Acid Armor',
    'Crabhammer',
    'Explosion',
    'Fury Swipes',
    'Bonemerang',
    'Rest',
    'Rock Slide',
    'Hyper Fang',
    'Sharpen',
    'Conversion',
    'Tri Attack',
    'Super Fang',
    'Slash',
    'Substitute',
    'Struggle',
    'Sketch',
    'Triple Kick',
    'Thief',
    'Spider Web',
    'Mind Reader',
    'Nightmare',
    'Flame Wheel',
    'Snore',
    'Curse',
    'Flail',
    'Conversion 2',
    'Aeroblast',
    'Cotton Spore',
    'Reversal',
    'Spite',
    'Powder Snow',
    'Protect',
    'Mach Punch',
    'Scary Face',
    'Feint Attack',
    'Sweet Kiss',
    'Belly Drum',
    'Sludge Bomb',
    'Mud-Slap',
    'Octazooka',
    'Spikes',
    'Zap Cannon',
    'Foresight',
    'Destiny Bond',
    'Perish Song',
    'Icy Wind',
    'Detect',
    'Bone Rush',
    'Lock-On',
    'Outrage',
    'Sandstorm',
    'Giga Drain',
    'Endure',
    'Charm',
    'Rollout',
    'False Swipe',
    'Swagger',
    'Milk Drink',
    'Spark',
    'Fury Cutter',
    'Steel Wing',
    'Mean Look',
    'Attract',
    'Sleep Talk',
    'Heal Bell',
    'Return',
    'Present',
    'Frustration',
    'Safeguard',
    'Pain Split',
    'Sacred Fire',
    'Magnitude',
    'Dynamic Punch',
    'Megahorn',
    'Dragon Breath',
    'Baton Pass',
    'Encore',
    'Pursuit',
    'Rapid Spin',
    'Sweet Scent',
    'Iron Tail',
    'Metal Claw',
    'Vital Throw',
    'Morning Sun',
    'Synthesis',
    'Moonlight',
    'Hidden Power',
    'Cross Chop',
    'Twister',
    'Rain Dance',
    'Sunny Day',
    'Crunch',
    'Mirror Coat',
    'Psych Up',
    'Extreme Speed',
    'Ancient Power',
    'Shadow Ball',
    'Future Sight',
    'Rock Smash',
    'Whirlpool',
    'Beat Up',
    'Fake Out',
    'Uproar',
    'Stockpile',
    'Spit Up',
    'Swallow',
    'Heat Wave',
    'Hail',
    'Torment',
    'Flatter',
    'Will-O-Wisp',
    'Memento',
    'Facade',
    'Focus Punch',
    'Smelling Salts',
    'Follow Me',
    'Nature Power',
    'Charge',
    'Taunt',
    'Helping Hand',
    'Trick',
    'Role Play',
    'Wish',
    'Assist',
    'Ingrain',
    'Superpower',
    'Magic Coat',
    'Recycle',
    'Revenge',
    'Brick Break',
    'Yawn',
    'Knock Off',
    'Endeavor',
    'Eruption',
    'Skill Swap',
    'Imprison',
    'Refresh',
    'Grudge',
    'Snatch',
    'Secret Power',
    'Dive',
    'Arm Thrust',
    'Camouflage',
    'Tail Glow',
    'Luster Purge',
    'Mist Ball',
    'Feather Dance',
    'Teeter Dance',
    'Blaze Kick',
    'Mud Sport',
    'Ice Ball',
    'Needle Arm',
    'Slack Off',
    'Hyper Voice',
    'Poison Fang',
    'Crush Claw',
    'Blast Burn',
    'Hydro Cannon',
    'Meteor Mash',
    'Astonish',
    'Weather Ball',
    'Aromatherapy',
    'Fake Tears',
    'Air Cutter',
    'Overheat',
    'Odor Sleuth',
    'Rock Tomb',
    'Silver Wind',
    'Metal Sound',
    'Grass Whistle',
    'Tickle',
    'Cosmic Power',
    'Water Spout',
    'Signal Beam',
    'Shadow Punch',
    'Extrasensory',
    'Sky Uppercut',
    'Sand Tomb',
    'Sheer Cold',
    'Muddy Water',
    'Bullet Seed',
    'Aerial Ace',
    'Icicle Spear',
    'Iron Defense',
    'Block',
    'Howl',
    'Dragon Claw',
    'Frenzy Plant',
    'Bulk Up',
    'Bounce',
    'Mud Shot',
    'Poison Tail',
    'Covet',
    'Volt Tackle',
    'Magical Leaf',
    'Water Sport',
    'Calm Mind',
    'Leaf Blade',
    'Dragon Dance',
    'Rock Blast',
    'Shock Wave',
    'Water Pulse',
    'Doom Desire',
    'Psycho Boost',
    'Roost',
    'Gravity',
    'Miracle Eye',
    'Wake-Up Slap',
    'Hammer Arm',
    'Gyro Ball',
    'Healing Wish',
    'Brine',
    'Natural Gift',
    'Feint',
    'Pluck',
    'Tailwind',
    'Acupressure',
    'Metal Burst',
    'U-turn',
    'Close Combat',
    'Payback',
    'Assurance',
    'Embargo',
    'Fling',
    'Psycho Shift',
    'Trump Card',
    'Heal Block',
    'Wring Out',
    'Power Trick',
    'Gastro Acid',
    'Lucky Chant',
    'Me First',
    'Copycat',
    'Power Swap',
    'Guard Swap',
    'Punishment',
    'Last Resort',
    'Worry Seed',
    'Sucker Punch',
    'Toxic Spikes',
    'Heart Swap',
    'Aqua Ring',
    'Magnet Rise',
    'Flare Blitz',
    'Force Palm',
    'Aura Sphere',
    'Rock Polish',
    'Poison Jab',
    'Dark Pulse',
    'Night Slash',
    'Aqua Tail',
    'Seed Bomb',
    'Air Slash',
    'X-Scissor',
    'Bug Buzz',
    'Dragon Pulse',
    'Dragon Rush',
    'Power Gem',
    'Drain Punch',
    'Vacuum Wave',
    'Focus Blast',
    'Energy Ball',
    'Brave Bird',
    'Earth Power',
    'Switcheroo',
    'Giga Impact',
    'Nasty Plot',
    'Bullet Punch',
    'Avalanche',
    'Ice Shard',
    'Shadow Claw',
    'Thunder Fang',
    'Ice Fang',
    'Fire Fang',
    'Shadow Sneak',
    'Mud Bomb',
    'Psycho Cut',
    'Zen Headbutt',
    'Mirror Shot',
    'Flash Cannon',
    'Rock Climb',
    'Defog',
    'Trick Room',
    'Draco Meteor',
    'Discharge',
    'Lava Plume',
    'Leaf Storm',
    'Power Whip',
    'Rock Wrecker',
    'Cross Poison',
    'Gunk Shot',
    'Iron Head',
    'Magnet Bomb',
    'Stone Edge',
    'Captivate',
    'Stealth Rock',
    'Grass Knot',
    'Chatter',
    'Judgment',
    'Bug Bite',
    'Charge Beam',
    'Wood Hammer',
    'Aqua Jet',
    'Attack Order',
    'Defend Order',
    'Heal Order',
    'Head Smash',
    'Double Hit',
    'Roar of Time',
    'Spacial Rend',
    'Lunar Dance',
    'Crush Grip',
    'Magma Storm',
    'Dark Void',
    'Seed Flare',
    'Ominous Wind',
    'Shadow Force',
    'Hone Claws',
    'Wide Guard',
    'Guard Split',
    'Power Split',
    'Wonder Room',
    'Psyshock',
    'Venoshock',
    'Autotomize',
    'Rage Powder',
    'Telekinesis',
    'Magic Room',
    'Smack Down',
    'Storm Throw',
    'Flame Burst',
    'Sludge Wave',
    'Quiver Dance',
    'Heavy Slam',
    'Synchronoise',
    'Electro Ball',
    'Soak',
    'Flame Charge',
    'Coil',
    'Low Sweep',
    'Acid Spray',
    'Foul Play',
    'Simple Beam',
    'Entrainment',
    'After You',
    'Round',
    'Echoed Voice',
    'Chip Away',
    'Clear Smog',
    'Stored Power',
    'Quick Guard',
    'Ally Switch',
    'Scald',
    'Shell Smash',
    'Heal Pulse',
    'Hex',
    'Sky Drop',
    'Shift Gear',
    'Circle Throw',
    'Incinerate',
    'Quash',
    'Acrobatics',
    'Reflect Type',
    'Retaliate',
    'Final Gambit',
    'Bestow',
    'Inferno',
    'Water Pledge',
    'Fire Pledge',
    'Grass Pledge',
    'Volt Switch',
    'Struggle Bug',
    'Bulldoze',
    'Frost Breath',
    'Dragon Tail',
    'Work Up',
    'Electroweb',
    'Wild Charge',
    'Drill Run',
    'Dual Chop',
    'Heart Stamp',
    'Horn Leech',
    'Sacred Sword',
    'Razor Shell',
    'Heat Crash',
    'Leaf Tornado',
    'Steamroller',
    'Cotton Guard',
    'Night Daze',
    'Psystrike',
    'Tail Slap',
    'Hurricane',
    'Head Charge',
    'Gear Grind',
    'Searing Shot',
    'Techno Blast',
    'Relic Song',
    'Secret Sword',
    'Glaciate',
    'Bolt Strike',
    'Blue Flare',
    'Fiery Dance',
    'Freeze Shock',
    'Ice Burn',
    'Snarl',
    'Icicle Crash',
    'V-create',
    'Fusion Flare',
    'Fusion Bolt',
    'Flying Press',
    'Mat Block',
    'Belch',
    'Rototiller',
    'Sticky Web',
    'Fell Stinger',
    'Phantom Force',
    'Trick-or-Treat',
    'Noble Roar',
    'Ion Deluge',
    'Parabolic Charge',
    "Forest's Curse",
    'Petal Blizzard',
    'Freeze-Dry',
    'Disarming Voice',
    'Parting Shot',
    'Topsy-Turvy',
    'Draining Kiss',
    'Crafty Shield',
    'Flower Shield',
    'Grassy Terrain',
    'Misty Terrain',
    'Electrify',
    'Play Rough',
    'Fairy Wind',
    'Moonblast',
    'Boomburst',
    'Fairy Lock',
    "King's Shield",
    'Play Nice',
    'Confide',
    'Diamond Storm',
    'Steam Eruption',
    'Hyperspace Hole',
    'Water Shuriken',
    'Mystical Fire',
    'Spiky Shield',
    'Aromatic Mist',
    'Eerie Impulse',
    'Venom Drench',
    'Powder',
    'Geomancy',
    'Magnetic Flux',
    'Happy Hour',
    'Electric Terrain',
    'Dazzling Gleam',
    'Celebrate',
    'Hold Hands',
    'Baby-Doll Eyes',
    'Nuzzle',
    'Hold Back',
    'Infestation',
    'Power-Up Punch',
    'Oblivion Wing',
    'Thousand Arrows',
    'Thousand Waves',
    "Land's Wrath",
    'Light of Ruin',
    'Origin Pulse',
    'Precipice Blades',
    'Dragon Ascent',
    'Hyperspace Fury',
    'Breakneck Blitz',
    'Breakneck Blitz',
    'All-Out Pummeling',
    'All-Out Pummeling',
    'Supersonic Skystrike',
    'Supersonic Skystrike',
    'Acid Downpour',
    'Acid Downpour',
    'Tectonic Rage',
    'Tectonic Rage',
    'Continental Crush',
    'Continental Crush',
    'Savage Spin-Out',
    'Savage Spin-Out',
    'Never-Ending Nightmare',
    'Never-Ending Nightmare',
    'Corkscrew Crash',
    'Corkscrew Crash',
    'Inferno Overdrive',
    'Inferno Overdrive',
    'Hydro Vortex',
    'Hydro Vortex',
    'Bloom Doom',
    'Bloom Doom',
    'Gigavolt Havoc',
    'Gigavolt Havoc',
    'Shattered Psyche',
    'Shattered Psyche',
    'Subzero Slammer',
    'Subzero Slammer',
    'Devastating Drake',
    'Devastating Drake',
    'Black Hole Eclipse',
    'Black Hole Eclipse',
    'Twinkle Tackle',
    'Twinkle Tackle',
    'Catastropika',
    'Shore Up',
    'First Impression',
    'Baneful Bunker',
    'Spirit Shackle',
    'Darkest Lariat',
    'Sparkling Aria',
    'Ice Hammer',
    'Floral Healing',
    'High Horsepower',
    'Strength Sap',
    'Solar Blade',
    'Leafage',
    'Spotlight',
    'Toxic Thread',
    'Laser Focus',
    'Gear Up',
    'Throat Chop',
    'Pollen Puff',
    'Anchor Shot',
    'Psychic Terrain',
    'Lunge',
    'Fire Lash',
    'Power Trip',
    'Burn Up',
    'Speed Swap',
    'Smart Strike',
    'Purify',
    'Revelation Dance',
    'Core Enforcer',
    'Trop Kick',
    'Instruct',
    'Beak Blast',
    'Clanging Scales',
    'Dragon Hammer',
    'Brutal Swing',
    'Aurora Veil',
    'Sinister Arrow Raid',
    'Malicious Moonsault',
    'Oceanic Operetta',
    'Guardian of Alola',
    'Soul-Stealing 7-Star Strike',
    'Stoked Sparksurfer',
    'Pulverizing Pancake',
    'Extreme Evoboost',
    'Genesis Supernova',
    'Shell Trap',
    'Fleur Cannon',
    'Psychic Fangs',
    'Stomping Tantrum',
    'Shadow Bone',
    'Accelerock',
    'Liquidation',
    'Prismatic Laser',
    'Spectral Thief',
    'Sunsteel Strike',
    'Moongeist Beam',
    'Tearful Look',
    'Zing Zap',
    "Nature's Madness",
    'Multi-Attack',
    '10,000,000 Volt Thunderbolt',
    'Mind Blown',
    'Plasma Fists',
    'Photon Geyser',
    'Light That Burns the Sky',
    'Searing Sunraze Smash',
    'Menacing Moonraze Maelstrom',
    "Let's Snuggle Forever",
    'Splintered Stormshards',
    'Clangorous Soulblaze',
];
