export enum Forme {
    // NOTE: Normal is not technically considered a "forme"
    Normal = 'Normal',

    A = 'a',
    B = 'b',
    C = 'c',
    D = 'd',
    E = 'e',
    F = 'f',
    G = 'g',
    H = 'h',
    I = 'i',
    J = 'j',
    K = 'k',
    L = 'l',
    M = 'm',
    N = 'n',
    O = 'o',
    P = 'p',
    Q = 'q',
    R = 'r',
    S = 's',
    T = 't',
    U = 'u',
    V = 'v',
    W = 'w',
    X = 'x',
    Y = 'y',
    Z = 'z',
    '!' = 'exclamation',
    '?' = 'question',

    Mega = 'mega',
    'Mega-X' = 'mega-x',
    'Mega-Y' = 'mega-y',

    Alolan = 'alola',
    Galarian = 'galar',
    Gigantamax = 'gigantamax',

    '10%' = '10-percent',
    '50%' = '50-percent',
    Complete = 'complete',

    Sunny = 'sunny',
    Rainy = 'rainy',
    Snowy = 'snowy',
}
