export const listOfAbilities = [
    'Adaptability',
    'Aerilate',
    'Aftermath',
    'Air Lock',
    'Analytic',
    'Anger Point',
    'Anticipation',
    'Arena Trap',
    'Aroma Veil',
    'Aura Break',
    'Bad Dreams',
    'Battery',
    'Battle Armor',
    'Battle Bond',
    'Beast Boost',
    'Berserk',
    'Big Pecks',
    'Blaze',
    'Bulletproof',
    'Cacophony',
    'Cheek Pouch',
    'Chlorophyll',
    'Clear Body',
    'Cloud Nine',
    'Color Change',
    'Comatose',
    'Competitive',
    'Compound Eyes',
    'Contrary',
    'Corrosion',
    'Cursed Body',
    'Cute Charm',
    'Damp',
    'Dancer',
    'Dark Aura',
    'Dazzling',
    'Defeatist',
    'Defiant',
    'Delta Stream',
    'Desolate Land',
    'Disguise',
    'Download',
    'Drizzle',
    'Drought',
    'Dry Skin',
    'Early Bird',
    'Effect Spore',
    'Electric Surge',
    'Emergency Exit',
    'Fairy Aura',
    'Filter',
    'Flame Body',
    'Flare Boost',
    'Flash Fire',
    'Flower Gift',
    'Flower Veil',
    'Fluffy',
    'Forecast',
    'Forewarn',
    'Friend Guard',
    'Frisk',
    'Full Metal Body',
    'Fur Coat',
    'Gale Wings',
    'Galvanize',
    'Gluttony',
    'Gooey',
    'Grass Pelt',
    'Grassy Surge',
    'Guts',
    'Harvest',
    'Healer',
    'Heatproof',
    'Heavy Metal',
    'Honey Gather',
    'Huge Power',
    'Hustle',
    'Hydration',
    'Hyper Cutter',
    'Ice Body',
    'Illuminate',
    'Illusion',
    'Immunity',
    'Imposter',
    'Infiltrator',
    'Innards Out',
    'Inner Focus',
    'Insomnia',
    'Intimidate',
    'Iron Barbs',
    'Iron Fist',
    'Justified',
    'Keen Eye',
    'Klutz',
    'Leaf Guard',
    'Levitate',
    'Light Metal',
    'Lightning Rod',
    'Limber',
    'Liquid Ooze',
    'Liquid Voice',
    'Long Reach',
    'Magic Bounce',
    'Magic Guard',
    'Magician',
    'Magma Armor',
    'Magnet Pull',
    'Marvel Scale',
    'Mega Launcher',
    'Merciless',
    'Minus',
    'Misty Surge',
    'Mold Breaker',
    'Moody',
    'Motor Drive',
    'Moxie',
    'Multiscale',
    'Multitype',
    'Mummy',
    'Natural Cure',
    'Neuroforce',
    'No Guard',
    'Normalize',
    'Oblivious',
    'Overcoat',
    'Overgrow',
    'Own Tempo',
    'Parental Bond',
    'Pickpocket',
    'Pickup',
    'Pixilate',
    'Plus',
    'Poison Heal',
    'Poison Point',
    'Poison Touch',
    'Power Construct',
    'Power of Alchemy',
    'Prankster',
    'Pressure',
    'Primordial Sea',
    'Prism Armor',
    'Protean',
    'Psychic Surge',
    'Pure Power',
    'Queenly Majesty',
    'Quick Feet',
    'Rain Dish',
    'Rattled',
    'Receiver',
    'Reckless',
    'Refrigerate',
    'Regenerator',
    'Rivalry',
    'RKS System',
    'Rock Head',
    'Rough Skin',
    'Run Away',
    'Sand Force',
    'Sand Rush',
    'Sand Stream',
    'Sand Veil',
    'Sap Sipper',
    'Schooling',
    'Scrappy',
    'Serene Grace',
    'Shadow Shield',
    'Shadow Tag',
    'Shed Skin',
    'Sheer Force',
    'Shell Armor',
    'Shield Dust',
    'Shields Down',
    'Simple',
    'Skill Link',
    'Slow Start',
    'Slush Rush',
    'Sniper',
    'Snow Cloak',
    'Snow Warning',
    'Solar Power',
    'Solid Rock',
    'Soul-Heart',
    'Soundproof',
    'Speed Boost',
    'Stakeout',
    'Stall',
    'Stamina',
    'Stance Change',
    'Static',
    'Steadfast',
    'Steelworker',
    'Stench',
    'Sticky Hold',
    'Storm Drain',
    'Strong Jaw',
    'Sturdy',
    'Suction Cups',
    'Super Luck',
    'Surge Surfer',
    'Swarm',
    'Sweet Veil',
    'Swift Swim',
    'Symbiosis',
    'Synchronize',
    'Tangled Feet',
    'Tangling Hair',
    'Technician',
    'Telepathy',
    'Teravolt',
    'Thick Fat',
    'Tinted Lens',
    'Torrent',
    'Tough Claws',
    'Toxic Boost',
    'Trace',
    'Triage',
    'Truant',
    'Turboblaze',
    'Unaware',
    'Unburden',
    'Unnerve',
    'Victory Star',
    'Vital Spirit',
    'Volt Absorb',
    'Water Absorb',
    'Water Bubble',
    'Water Compaction',
    'Water Veil',
    'Weak Armor',
    'White Smoke',
    'Wimp Out',
    'Wonder Guard',
    'Wonder Skin',
    'Zen Mode',
];
