export const listOfLocations = [
    // Kanto
    'Route 1',
    'Route 2',
    'Route 3',
    'Route 4',
    'Route 5',
    'Route 6',
    'Route 7',
    'Route 8',
    'Route 9',
    'Route 10',
    'Route 11',
    'Route 12',
    'Route 13',
    'Route 14',
    'Route 15',
    'Route 16',
    'Route 17',
    'Route 18',
    'Route 19',
    'Route 20',
    'Route 21',
    'Route 22',
    'Route 23',
    'Route 24',
    'Route 25',
    'Route 26',
    'Route 27',
    'Route 28',
    'Berry Forest',
    'Bond Bridge',
    'Canyon Entrance',
    'Cape Brink',
    'Celadon City',
    'Cerulean Cave',
    'Cerulean City',
    'Cinnabar Island',
    'Diglett\'s Cave',
    'Five Island',
    'Five Isle Meadow',
    'Four Island',
    'Fuchsia City',
    'Green Path',
    'Icefall Cave',
    'Kindle Road',
    'Lost Cave',
    'Memorial Pillar',
    'Mt. Ember',
    'Mt. Moon',
    'One Island',
    'Outcast Island',
    'Pallet Town',
    'Pattern Bush',
    'Pewter City',
    'Pokémon Mansion',
    'Pokémon Tower',
    'Power Plant',
    'Resort Gorgeous',
    'Rock Tunnel',
    'Ruin Valley',
    'Safari Zone',
    'Saffron City',
    'Seafoam Islands',
    'Seavault Canyon',
    'Silph Co',
    'Tanoby Ruins',
    'Three Isle Port',
    'Tohjo Falls',
    'Trainer Tower',
    'Treasure Beach',
    'Vermilion City',
    'Victory Road',
    'Viridian City',
    'Viridian Forest',
    'Water Labyrinth',
    'Water Path',
    // Johto
    'Route 29',
    'Route 30',
    'Route 31',
    'Route 32',
    'Route 33',
    'Route 34',
    'Route 35',
    'Route 36',
    'Route 37',
    'Route 38',
    'Route 39',
    'Route 40',
    'Route 41',
    'Route 42',
    'Route 43',
    'Route 44',
    'Route 45',
    'Route 46',
    'Route 47',
    'Route 48',
    'Azalea Town',
    'Bell Tower',
    'Blackthorn City',
    'Burned Tower',
    'Cherrygrove City',
    'Cianwood City',
    'Cliff Cave',
    'Cliff Edge Gate',
    'Dark Cave',
    'Dragon\'s Den',
    'Ecruteak City',
    'Embedded Tower',
    'Goldenrod City',
    'Ice Path',
    'Ilex Forest',
    'Lake of Rage',
    'Mt. Mortar',
    'Mt. Silver',
    'National Park',
    'New Bark Town',
    'Olivine City',
    'Ruins of Alph',
    'Safari Zone Gate',
    'Slowpoke Well',
    'Sprout Tower',
    'Team Rocket HQ',
    'Tin Tower',
    'Union Cave',
    'Violet City',
    'Whirl Islands',
    // Hoenn
    'Route 101',
    'Route 102',
    'Route 103',
    'Route 104',
    'Route 105',
    'Route 106',
    'Route 107',
    'Route 108',
    'Route 109',
    'Route 110',
    'Route 111',
    'Route 112',
    'Route 113',
    'Route 114',
    'Route 115',
    'Route 116',
    'Route 117',
    'Route 118',
    'Route 119',
    'Route 120',
    'Route 121',
    'Route 122',
    'Route 123',
    'Route 124',
    'Route 125',
    'Route 126',
    'Route 127',
    'Route 128',
    'Route 129',
    'Route 130',
    'Route 131',
    'Route 132',
    'Route 133',
    'Route 134',
    'Abandoned Ship',
    'Altering Cave',
    'Artisan Cave',
    'Battle Resort',
    'Battle Tower',
    'Birth Island',
    'Cave of Origin',
    'Desert Underpass',
    'Dewford Town',
    'Ever Grande City',
    'Faraway Island',
    'Fiery Path',
    'Fortree City',
    'Granite Cave',
    'Jagged Pass',
    'Lilycove City',
    'Littleroot Town',
    'Magma Hideout',
    'Marine Cave',
    'Meteor Falls',
    'Mirage Island',
    'Mirage Spots',
    'Mirage Tower',
    'Mossdeep City',
    'Mt. Pyre',
    'Navel Rock',
    'New Mauville',
    'Pacifidlog Town',
    'Petalburg City',
    'Petalburg Woods',
    'Rustboro City',
    'Rusturf Tunnel',
    'Safari Zone',
    'Scorched Slab',
    'Sea Mauville',
    'Seafloor Cavern',
    'Sealed Chamber',
    'Shoal Cave',
    'Sky Pillar',
    'Slateport City',
    'Sootopolis City',
    'Southern Island',
    'Team Magma/Aqua Hideout',
    'Terra Cave',
    'Victory Road',
    // Unova
    'Route 1',
    'Route 2',
    'Route 3',
    'Route 4',
    'Route 5',
    'Route 6',
    'Route 7',
    'Route 8',
    'Route 9',
    'Route 10',
    'Route 11',
    'Route 12',
    'Route 13',
    'Route 14',
    'Route 15',
    'Route 16',
    'Route 17',
    'Route 18',
    'Route 19',
    'Route 20',
    'Route 21',
    'Route 22',
    'Route 23',
    'Abundant Shrine',
    'Accumula Town',
    'Aspertia City',
    'Castelia City',
    'Castelia Sewers',
    'Celestial Tower',
    'Challenger\'s Cave',
    'Chargestone Cave',
    'Clay Tunnel',
    'Cold Storage',
    'Desert Resort',
    'Dragonspiral Tower',
    'Dreamyard',
    'Driftveil City',
    'Driftveil Drawbridge',
    'Floccesy Ranch',
    'Giant Chasm',
    'Humilau City',
    'Icirrus City',
    'Liberty Island',
    'Lostlorn Forest',
    'Marvelous Bridge',
    'Mistralton Cave',
    'Moor of Icirrus',
    'N\'s Castle',
    'Nacrene City',
    'Nature Preserve',
    'Nature Sanctuary',
    'Nuvema Town',
    'P2 Laboratory',
    'Pinwheel Forest',
    'Relic Castle',
    'Relic Passage',
    'Reversal Mountain',
    'Seaside Cave',
    'Strange House',
    'Striaton City',
    'Twist Mountain',
    'Undella Bay',
    'Undella Town',
    'Underground Ruins',
    'Victory Road',
    'Village Bridge',
    'Virbank City',
    'Virbank Complex',
    'Wellspring Cave',
    'White Forest',
    // Sinnoh
    'Route 201',
    'Route 202',
    'Route 203',
    'Route 204',
    'Route 205',
    'Route 206',
    'Route 207',
    'Route 208',
    'Route 209',
    'Route 210',
    'Route 211',
    'Route 212',
    'Route 213',
    'Route 214',
    'Route 215',
    'Route 216',
    'Route 217',
    'Route 218',
    'Route 219',
    'Route 220',
    'Route 221',
    'Route 222',
    'Route 223',
    'Route 224',
    'Route 225',
    'Route 226',
    'Route 227',
    'Route 228',
    'Route 229',
    'Route 230',
    'Acuity Lakefront',
    'Canalave City',
    'Celestic Town',
    'Distortion World',
    'Eterna City',
    'Eterna Forest',
    'Floaroma Meadow',
    'Flower Paradise',
    'Fuego Ironworks',
    'Great Marsh',
    'Hall of Origin',
    'Iron Island',
    'Lake Acuity',
    'Lake Valor',
    'Lake Verity',
    'Lost Tower',
    'Mt. Coronet',
    'Newmoon Island',
    'Old Chateau',
    'Oreburgh City',
    'Oreburgh Gate',
    'Oreburgh Mine',
    'Pastoria City',
    'Pokémon League',
    'Ravaged Path',
    'Resort Area',
    'Ruins Maniac\'s Cave',
    'Ruins Maniac\'s Tunnel',
    'Sendoff Spring',
    'Snowpoint City',
    'Snowpoint Temple',
    'Solaceon Ruins',
    'Spear Pillar',
    'Stark Mountain',
    'Sunyshore City',
    'Trophy Garden',
    'Turnback Cave',
    'Twinleaf Town',
    'Valley Windworks',
    'Valor Lakefront',
    'Victory Road',
    'Wayward Cave',
    // Kalos
    'Route 2',
    'Route 3',
    'Route 4',
    'Route 5',
    'Route 6',
    'Route 7',
    'Route 8',
    'Route 9',
    'Route 10',
    'Route 11',
    'Route 12',
    'Route 13',
    'Route 14',
    'Route 15',
    'Route 16',
    'Route 17',
    'Route 18',
    'Route 19',
    'Route 20',
    'Route 21',
    'Route 22',
    'Ambrette Town',
    'Aquacorde Town',
    'Azure Bay',
    'Connecting Cave',
    'Couriway Town',
    'Cyllage City',
    'Frost Cavern',
    'Glittering Cave',
    'Laverre City',
    'Lost Hotel',
    'Lumiose City',
    'Parfum Palace',
    'Pokémon Village',
    'Reflection Cave',
    'Santalune City',
    'Santalune Forest',
    'Sea Spirit\'s Den',
    'Shalour City',
    'Snowbelle City',
    'Team Flare HQ',
    'Terminus Cave',
    'Tower of Mastery',
    'Unknown Dungeon',
    'Vaniville Town',
    'Victory Road',
    // Alola
    'Route 1',
    'Route 2',
    'Route 3',
    'Route 4',
    'Route 5',
    'Route 6',
    'Route 7',
    'Route 8',
    'Route 9',
    'Route 10',
    'Route 11',
    'Route 12',
    'Route 13',
    'Route 14',
    'Route 15',
    'Route 16',
    'Route 17',
    'Aether Paradise',
    'Akala Outskirts',
    'Altar of the Moone',
    'Altar of the Sunne',
    'Ancient Poni Path',
    'Berry Fields',
    'Blush Mountain',
    'Brooklet Hill',
    'Diglett\'s Tunnel',
    'Dividing Peak Tunnel',
    'Exeggutor Island',
    'Haina Desert',
    'Hano Beach',
    'Hau\'oli Cemetery',
    'Hau\'oli City',
    'Heahea Beach',
    'Iki Town',
    'Kala\'e Bay',
    'Lake of the Moone',
    'Lake of the Sunne',
    'Lush Jungle',
    'Malie City',
    'Malie Garden',
    'Melemele Meadow',
    'Melemele Sea',
    'Memorial Hill',
    'Mount Hokulani',
    'Mount Lanakila',
    'Paniola Ranch',
    'Paniola Town',
    'Poni Breaker Coast',
    'Poni Coast',
    'Poni Gauntlet',
    'Poni Grove',
    'Poni Meadow',
    'Poni Plains',
    'Poni Wilds',
    'Resolution Cave',
    'Ruins of Abundance',
    'Ruins of Conflict',
    'Ruins of Hope',
    'Ruins of Life',
    'Sandy Cave',
    'Seafolk Village',
    'Seaward Cave',
    'Secluded Shore',
    'Tapu Village',
    'Ten Carat Hill',
    'Thrifty Megamart',
    'Ula\'ula Beach',
    'Ula\'ula Meadow',
    'Ultra Megalopolis',
    'Ultra Space',
    'Ultra Space Wilds',
    'Vast Poni Canyon',
    'Verdant Cavern',
    'Wela Volcano Park',
    // Galar
    'Postwick',
    'Wedgehurst',
    'Motostoke',
    'Turrfield',
    'Hulbury',
    'Hammerlocke',
    'Stow-on-Side',
    'Ballonlea',
    'Circhester',
    'Spikemuth',
    'Wyndon',
    'Route 1',
    'Route 2',
    'Route 3',
    'Route 4',
    'Route 5',
    'Route 6',
    'Route 7',
    'Route 8',
    'Route 9',
    'Route 10',
    'Meetup Spot',
    'Rolling Fields',
    'Dappled Grove',
    'Watchtower Ruins',
    'East Lake Axewell',
    'West Lake Axewell',
    'Axew\'s Eye',
    'South Lake Miloch',
    'Giant\'s Seat',
    'North Lake Miloch',
    'Motostoke Riverbank',
    'Bridge Field',
    'Stony Wilderness',
    'Dusty Bowl',
    'Giant\'s Mirror',
    'Hammerlocke Hills',
    'Giant\'s Cap',
    'Lake of Outrage',
];
