export const listOfGames = [
    'Red',
    'Blue',
    'Green',
    'Yellow',
    'Gold',
    'Silver',
    'Crystal',
    'Ruby',
    'Sapphire',
    'Emerald',
    'Diamond',
    'Pearl',
    'Platinum',
    'HeartGold',
    'SoulSilver',
    'Black',
    'White',
    'Black 2',
    'White 2',
    'X',
    'Y',
    'OmegaRuby',
    'AlphaSapphire',
    'Sun',
    'Moon',
    'Ultra Sun',
    'Ultra Moon',
    //'Custom...',
];
