export const listOfItems = [
    'Absorb Bulb',
    'Adamant Orb',
    'Adrenaline Orb',
    'Air Balloon',
    'Amulet Coin',
    'Assault Vest',
    'Big Root',
    'Binding Band',
    'Black Belt',
    'Black Glasses',
    'Black Sludge',
    'Blue Orb',
    'Bright Powder',
    'Burn Drive',
    'Cell Battery',
    'Charcoal',
    'Chill Drive',
    'Choice Band',
    'Choice Scarf',
    'Choice Specs',
    'Cleanse Tag',
    'Damp Rock',
    'Destiny Knot',
    'Douse Drive',
    'Dragon Fang',
    'Eject Button',
    'Electric Seed',
    'Everstone',
    'Eviolite',
    'Exp Share',
    'Expert Belt',
    'Flame Orb',
    'Float Stone',
    'Focus Band',
    'Focus Sash',
    'Grassy Seed',
    'Grip Claw',
    'Griseous Orb',
    'Hard Stone',
    'Heat Rock',
    'Icy Rock',
    'Iron Ball',
    'Kings Rock',
    'Lagging Tail',
    'Leftovers',
    'Life Orb',
    'Light Ball',
    'Light Clay',
    'Lucky Egg',
    'Lucky Punch',
    'Luminous Moss',
    'Lustrous Orb',
    'Magnet',
    'Mental Herb',
    'Metal Coat',
    'Metal Powder',
    'Metronome',
    'Miracle Seed',
    'Misty Seed',
    'Muscle Band',
    'Mystic Water',
    'Never Melt Ice',
    'Poison Barb',
    'Power Herb',
    'Protective Pads',
    'Psychic Seed',
    'Quick Claw',
    'Quick Powder',
    'Red Card',
    'Red Orb',
    'Ring Target',
    'Rocky Helmet',
    'Safety Helmet',
    'Scope Lens',
    'Sharp Beak',
    'Shed Shell',
    'Shock Drive',
    'Silk Scarf',
    'Silver Powder',
    'Smoke Ball',
    'Smooth Rock',
    'Snowball',
    'Soft Sand',
    'Soul Dew',
    'Spell Tag',
    'Stick',
    'Sticky Barb',
    'Terrain Extender',
    'Thick Club',
    'Toxic Orb',
    'Twisted Spoon',
    'Weakness Policy',
    'White Herb',
    'Wide Lens',
    'Wise Glasses',
    'Zoom Lens'
];
