export enum Nature {
    Adamant = 'Adamant',
    Bashful = 'Bashful',
    Bold    = 'Bold',
    Brave   = 'Brave',
    Calm    = 'Calm',
    Careful = 'Careful',
    Docile  = 'Docile',
    Gentle  = 'Gentle',
    Hardy   = 'Hardy',
    Hasty   = 'Hasty',
    Impish  = 'Impish',
    Jolly   = 'Jolly',
    Lax     = 'Lax',
    Lonely  = 'Lonely',
    Mild    = 'Mild',
    Modest  = 'Modest',
    Naive   = 'Naive',
    Naughty = 'Naughty',
    Quiet   = 'Quiet',
    Quirky  = 'Quirky',
    Rash    = 'Rash',
    Relaxed = 'Relaxed',
    Sassy   = 'Sassy',
    Serious = 'Serious',
    Timid   = 'Timid',
    None    = 'None',
}