export const styleDefaults = {
    backgroundImage: '',
    bgColor: '#383840',
    customCSS: ``,
    iconsNextToTeamPokemon: false,
    imageStyle: 'round',
    minimalTeamLayout: false,
    movesPosition: 'horizontal',
    resultHeight: '900',
    resultWidth: '1200',
    teamImages: 'standard',
    teamPokemonBorder: true,
    displayRules: false,
    editorDarkMode: false,
    template: 'Default Dark',
    topHeaderColor: '#333333',
};
